Reinstate ARM64 and UB (CI will fail - lack of FFTS support)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,12 +43,12 @@ jobs:
             cmake_preset: "macos-packaging-release"
             vcpkg_triplet: x64-osx-10_13
             test: true
-          # - name: "macOS Latest Clang arm64"
-            # os: macos-latest
-            # package: true
-            # cmake_preset: "macos-arm64-packaging-release"
-            # vcpkg_triplet: arm64-osx
-            # test: false
+          - name: "macOS Latest Clang arm64"
+            os: macos-latest
+            package: true
+            cmake_preset: "macos-arm64-packaging-release"
+            vcpkg_triplet: arm64-osx
+            test: false
     steps:
            
       - name: 'Checkout repo'
@@ -182,58 +182,58 @@ jobs:
           name: ${{ steps.cmake_install_prefix.outputs.install_dir }}
           path: ${{ steps.cmake_install_prefix.outputs.install_prefix }}
 
-  # mac_universal_bin:
-    # name: mac_universal_bin
-    # runs-on: macos-latest
-    # needs: build
+  mac_universal_bin:
+    name: mac_universal_bin
+    runs-on: macos-latest
+    needs: build
 
-    # steps:
-      # - uses: actions/download-artifact@v2
-        # with:
-          # name: 'macOS_Latest_Clang_x64'
-          # path: 'macOS_Latest_Clang_x64'
+    steps:
+      - uses: actions/download-artifact@v2
+        with:
+          name: 'macOS_Latest_Clang_x64'
+          path: 'macOS_Latest_Clang_x64'
 
-      # - uses: actions/download-artifact@v2
-        # with:
-          # name: 'macOS_Latest_Clang_arm64'
-          # path: 'macOS_Latest_Clang_arm64'
+      - uses: actions/download-artifact@v2
+        with:
+          name: 'macOS_Latest_Clang_arm64'
+          path: 'macOS_Latest_Clang_arm64'
 
-      # - name: 'build ub'
-        # run: |
-          # intel_dir="macOS_Latest_Clang_x64"
-          # arm_dir="macOS_Latest_Clang_arm64"
-          # ub_dir="macOS_Latest_Clang_universal"
+      - name: 'build ub'
+        run: |
+          intel_dir="macOS_Latest_Clang_x64"
+          arm_dir="macOS_Latest_Clang_arm64"
+          ub_dir="macOS_Latest_Clang_universal"
           
-          # cp -r $intel_dir $ub_dir
+          cp -r $intel_dir $ub_dir
           
-          # function make_ub() {
-            # intel_bin="$1"
-            # arm_bin=$(echo "$intel_bin" | sed "s:$intel_dir:$arm_dir:")
-            # ub_bin=$(echo "$intel_bin" | sed "s:$intel_dir:$ub_dir:")
+          function make_ub() {
+            intel_bin="$1"
+            arm_bin=$(echo "$intel_bin" | sed "s:$intel_dir:$arm_dir:")
+            ub_bin=$(echo "$intel_bin" | sed "s:$intel_dir:$ub_dir:")
             
-            # if [ ! -f "$arm_bin" ]; then
-              # echo "$arm_bin not found"
-              # exit 1
-            # fi
+            if [ ! -f "$arm_bin" ]; then
+              echo "$arm_bin not found"
+              exit 1
+            fi
             
-            # lipo "$intel_bin" "$arm_bin" -create -output "$ub_bin"
-          # }
+            lipo "$intel_bin" "$arm_bin" -create -output "$ub_bin"
+          }
           
-          # LIBS=`find $intel_dir -name '*.dylib'`
-          # PLUGINS=`find $intel_dir -path '*vst3/Contents/MacOS/*'`
+          LIBS=`find $intel_dir -name '*.dylib'`
+          PLUGINS=`find $intel_dir -path '*vst3/Contents/MacOS/*'`
           
-          # IFS=$'\n'
-          # for lib in $LIBS; do
-            # echo "Making UB Library from: $lib"
-            # make_ub "$lib"
-          # done
+          IFS=$'\n'
+          for lib in $LIBS; do
+            echo "Making UB Library from: $lib"
+            make_ub "$lib"
+          done
           
-          # for plugin in $PLUGINS; do
-            # echo "Making UB Plugin from: $plugin"
-            # make_ub "$plugin"
-          # done
+          for plugin in $PLUGINS; do
+            echo "Making UB Plugin from: $plugin"
+            make_ub "$plugin"
+          done
 
-      # - uses: actions/upload-artifact@v2
-        # with:
-          # name: 'macOS_Latest_Clang_universal'
-          # path: 'macOS_Latest_Clang_universal'
+      - uses: actions/upload-artifact@v2
+        with:
+          name: 'macOS_Latest_Clang_universal'
+          path: 'macOS_Latest_Clang_universal'
