Temp build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -37,25 +37,29 @@ jobs:
             # cmake_preset: "windows-packaging-relwithdebinfo"
             # vcpkg_triplet: x64-windows-static
             # test: true
-          - name: "macOS Latest Clang x64"
-            os: macos-latest
-            package: true
-            cmake_preset: "macos-packaging-release"
-            vcpkg_triplet: x64-osx-10_13
-            test: true
-          - name: "macOS Latest Clang arm64"
-            os: macos-latest
-            package: true
-            cmake_preset: "macos-arm64-packaging-release"
-            vcpkg_triplet: arm64-osx-11_0
-            test: false
-          - name: "Ubuntu 20.04"
-            os: ubuntu-20.04
-            package: true
-            cmake_preset: "linux-packaging-release"
-            vcpkg_triplet: x64-linux
-            test: true
+          # - name: "macOS Latest Clang x64"
+            # os: macos-latest
+            # package: true
+            # cmake_preset: "macos-packaging-release"
+            # vcpkg_triplet: x64-osx-10_13
+            # test: true
+          # - name: "macOS Latest Clang arm64"
+            # os: macos-latest
+            # package: true
+            # cmake_preset: "macos-arm64-packaging-release"
+            # vcpkg_triplet: arm64-osx-11_0
+            # test: false
+          # - name: "Ubuntu 20.04"
+            # os: ubuntu-20.04
+            # package: true
+            # cmake_preset: "linux-packaging-release"
+            # vcpkg_triplet: x64-linux
+            # test: true
     steps:
+      - name: 'Disks'
+        if: matrix.config.os == 'windows-latest'
+        run: Get-PSDrive
+
       - name: 'Checkout repo recursively.'
         uses: actions/checkout@v3
         with:
@@ -196,90 +200,90 @@ jobs:
           name: ${{ steps.cmake_install_prefix.outputs.install_dir }}
           path: ${{ steps.cmake_install_prefix.outputs.install_prefix }}
 
-  mac_universal_bin:
-    name: mac_universal_bin
-    runs-on: macos-latest
-    needs: build
+  # mac_universal_bin:
+    # name: mac_universal_bin
+    # runs-on: macos-latest
+    # needs: build
 
-    steps:
-      - uses: actions/download-artifact@v2
-        with:
-          name: 'macOS_Latest_Clang_x64'
-          path: 'macOS_Latest_Clang_x64'
+    # steps:
+      # - uses: actions/download-artifact@v2
+        # with:
+          # name: 'macOS_Latest_Clang_x64'
+          # path: 'macOS_Latest_Clang_x64'
 
-      - uses: actions/download-artifact@v2
-        with:
-          name: 'macOS_Latest_Clang_arm64'
-          path: 'macOS_Latest_Clang_arm64'
+      # - uses: actions/download-artifact@v2
+        # with:
+          # name: 'macOS_Latest_Clang_arm64'
+          # path: 'macOS_Latest_Clang_arm64'
         
-      - name: 'un-tar x64'
-        run: tar -xf macOS_Latest_Clang_x64.tar && rm macOS_Latest_Clang_x64.tar
-        working-directory: macOS_Latest_Clang_x64
+      # - name: 'un-tar x64'
+        # run: tar -xf macOS_Latest_Clang_x64.tar && rm macOS_Latest_Clang_x64.tar
+        # working-directory: macOS_Latest_Clang_x64
         
-      - name: 'un-tar arm64'
-        run: tar -xf macOS_Latest_Clang_arm64.tar && rm macOS_Latest_Clang_arm64.tar
-        working-directory: macOS_Latest_Clang_arm64
+      # - name: 'un-tar arm64'
+        # run: tar -xf macOS_Latest_Clang_arm64.tar && rm macOS_Latest_Clang_arm64.tar
+        # working-directory: macOS_Latest_Clang_arm64
         
-      - name: 'dir listing'
-        run: ls -R
+      # - name: 'dir listing'
+        # run: ls -R
 
-      - name: 'build ub'
-        run: |
-          intel_dir="macOS_Latest_Clang_x64"
-          arm_dir="macOS_Latest_Clang_arm64"
-          ub_dir="macOS_Latest_Clang_universal"
+      # - name: 'build ub'
+        # run: |
+          # intel_dir="macOS_Latest_Clang_x64"
+          # arm_dir="macOS_Latest_Clang_arm64"
+          # ub_dir="macOS_Latest_Clang_universal"
           
-          cp -r $intel_dir $ub_dir
+          # cp -r $intel_dir $ub_dir
           
-          function make_ub() {
-            intel_bin="$1"
-            arm_bin=$(echo "$intel_bin" | sed "s:$intel_dir:$arm_dir:")
-            ub_bin=$(echo "$intel_bin" | sed "s:$intel_dir:$ub_dir:")
+          # function make_ub() {
+            # intel_bin="$1"
+            # arm_bin=$(echo "$intel_bin" | sed "s:$intel_dir:$arm_dir:")
+            # ub_bin=$(echo "$intel_bin" | sed "s:$intel_dir:$ub_dir:")
             
-            if [ ! -f "$arm_bin" ]; then
-              echo "$arm_bin not found"
-              exit 1
-            fi
+            # if [ ! -f "$arm_bin" ]; then
+              # echo "$arm_bin not found"
+              # exit 1
+            # fi
             
-            lipo "$intel_bin" "$arm_bin" -create -output "$ub_bin"
-          }
+            # lipo "$intel_bin" "$arm_bin" -create -output "$ub_bin"
+          # }
           
-          LIBS=`find $intel_dir -name '*.dylib'`
-          # note: "! -name '*.*'" excludes files with an extension (auxiliary files)
-          PLUGINS=`find $intel_dir -path '*vst3/Contents/MacOS/*' ! -name '*.*'`
-          APPS=`find $intel_dir -path '*app/Contents/MacOS/*' ! -name '*.*'`
-          # don't forget project upgrade command line util
-          EXES=`find $intel_dir -name 'project_upgrade'`
+          # LIBS=`find $intel_dir -name '*.dylib'`
+          # # note: "! -name '*.*'" excludes files with an extension (auxiliary files)
+          # PLUGINS=`find $intel_dir -path '*vst3/Contents/MacOS/*' ! -name '*.*'`
+          # APPS=`find $intel_dir -path '*app/Contents/MacOS/*' ! -name '*.*'`
+          # # don't forget project upgrade command line util
+          # EXES=`find $intel_dir -name 'project_upgrade'`
           
-          IFS=$'\n'
+          # IFS=$'\n'
           
-          for exe in $EXES; do
-            echo "Making UB Exectuable from: $exe"
-            make_ub "$exe"
-          done
+          # for exe in $EXES; do
+            # echo "Making UB Exectuable from: $exe"
+            # make_ub "$exe"
+          # done
 
-          for lib in $LIBS; do
-            echo "Making UB Library from: $lib"
-            make_ub "$lib"
-          done
+          # for lib in $LIBS; do
+            # echo "Making UB Library from: $lib"
+            # make_ub "$lib"
+          # done
           
-          for plugin in $PLUGINS; do
-            echo "Making UB Plugin from: $plugin"
-            make_ub "$plugin"
-          done
+          # for plugin in $PLUGINS; do
+            # echo "Making UB Plugin from: $plugin"
+            # make_ub "$plugin"
+          # done
           
-          for app in $APPS; do
-            echo "Making UB App from: $app"
-            make_ub "$app"
-          done
+          # for app in $APPS; do
+            # echo "Making UB App from: $app"
+            # make_ub "$app"
+          # done
           
-      - name: 'dir listing'
-        run: ls -R
+      # - name: 'dir listing'
+        # run: ls -R
           
-      - name: 'tar ub'
-        run: tar -cvf macOS_Latest_Clang_universal.tar -C macOS_Latest_Clang_universal .
+      # - name: 'tar ub'
+        # run: tar -cvf macOS_Latest_Clang_universal.tar -C macOS_Latest_Clang_universal .
 
-      - uses: actions/upload-artifact@v2
-        with:
-          name: 'macOS_Latest_Clang_universal'
-          path: 'macOS_Latest_Clang_universal.tar'
+      # - uses: actions/upload-artifact@v2
+        # with:
+          # name: 'macOS_Latest_Clang_universal'
+          # path: 'macOS_Latest_Clang_universal.tar'
